version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

formats: all

python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
